"""Boost unique name

Revision ID: 7203ca5a2dee
Revises: a427b5be5ed7
Create Date: 2024-11-16 15:44:53.137852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7203ca5a2dee'
down_revision: Union[str, None] = 'a427b5be5ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'boost', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boost', type_='unique')
    # ### end Alembic commands ###
