"""Int upgrade cost

Revision ID: 8c0a8d6d7e98
Revises: 7203ca5a2dee
Create Date: 2024-11-16 16:04:16.144647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0a8d6d7e98'
down_revision: Union[str, None] = '7203ca5a2dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boost', 'cost_per_level',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boost', 'cost_per_level',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
