"""User photo

Revision ID: e748d9993849
Revises: 4b3fccd2a11a
Create Date: 2024-11-17 11:23:21.524110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e748d9993849'
down_revision: Union[str, None] = '4b3fccd2a11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###
